package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3168767489891290408L;
	private Long id;
	private String title;
	private long parentId;
	private String slug;
	private Character isActive;
	private Character isDeleted;

	public Categories() {
	}

	public Categories(long parentId) {
		this.parentId = parentId;
	}

	public Categories(String title, long parentId, String slug,
			Character isActive, Character isDeleted) {
		this.title = title;
		this.parentId = parentId;
		this.slug = slug;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public long getParentId() {
		return this.parentId;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	public Character getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Character isDeleted) {
		this.isDeleted = isDeleted;
	}

}
