package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * CmsPages generated by hbm2java
 */
public class CmsPages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1986701314705815589L;
	private Integer id;
	private String title;
	private Integer categoryId;
	private String slug;
	private String metaTitle;
	private String metaDescription;
	private String metaKeywords;
	private String metaContent;
	private Byte sortOrder;
	private Character isActive;
	private Character isDeleted;

	public CmsPages() {
	}

	public CmsPages(String title, Integer categoryId, String slug,
			String metaTitle, String metaDescription, String metaKeywords,
			String metaContent, Byte sortOrder, Character isActive,
			Character isDeleted) {
		this.title = title;
		this.categoryId = categoryId;
		this.slug = slug;
		this.metaTitle = metaTitle;
		this.metaDescription = metaDescription;
		this.metaKeywords = metaKeywords;
		this.metaContent = metaContent;
		this.sortOrder = sortOrder;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public String getMetaTitle() {
		return this.metaTitle;
	}

	public void setMetaTitle(String metaTitle) {
		this.metaTitle = metaTitle;
	}

	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	public String getMetaContent() {
		return this.metaContent;
	}

	public void setMetaContent(String metaContent) {
		this.metaContent = metaContent;
	}

	public Byte getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Byte sortOrder) {
		this.sortOrder = sortOrder;
	}

	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	public Character getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Character isDeleted) {
		this.isDeleted = isDeleted;
	}

}
