package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MobileNetworks generated by hbm2java
 */
public class MobileNetworks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1277809716366337826L;
	private Long id;
	private String title;
	private String type;
	private Character isActive;
	private Character isDeleted;
	private Set<?> mobilePhoneToNetworkses = new HashSet<Object>(0);

	public MobileNetworks() {
	}

	public MobileNetworks(String title, String type, Character isActive,
			Character isDeleted, Set<?> mobilePhoneToNetworkses) {
		this.title = title;
		this.type = type;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.mobilePhoneToNetworkses = mobilePhoneToNetworkses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	public Character getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Character isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<?> getMobilePhoneToNetworkses() {
		return this.mobilePhoneToNetworkses;
	}

	public void setMobilePhoneToNetworkses(Set<?> mobilePhoneToNetworkses) {
		this.mobilePhoneToNetworkses = mobilePhoneToNetworkses;
	}

}
