package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToNetworks generated by hbm2java
 */
public class MobilePhoneToNetworks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7811464520248787616L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileNetworks mobileNetworks;

	public MobilePhoneToNetworks() {
	}

	public MobilePhoneToNetworks(MobilePhones mobilePhones,
			MobileNetworks mobileNetworks) {
		this.mobilePhones = mobilePhones;
		this.mobileNetworks = mobileNetworks;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileNetworks getMobileNetworks() {
		return this.mobileNetworks;
	}

	public void setMobileNetworks(MobileNetworks mobileNetworks) {
		this.mobileNetworks = mobileNetworks;
	}

}
