package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToProtections generated by hbm2java
 */
public class MobilePhoneToProtections implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5448464005565218042L;
	private Long id;
	private MobileDisplayProtection mobileDisplayProtection;
	private MobilePhones mobilePhones;

	public MobilePhoneToProtections() {
	}

	public MobilePhoneToProtections(
			MobileDisplayProtection mobileDisplayProtection,
			MobilePhones mobilePhones) {
		this.mobileDisplayProtection = mobileDisplayProtection;
		this.mobilePhones = mobilePhones;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobileDisplayProtection getMobileDisplayProtection() {
		return this.mobileDisplayProtection;
	}

	public void setMobileDisplayProtection(
			MobileDisplayProtection mobileDisplayProtection) {
		this.mobileDisplayProtection = mobileDisplayProtection;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

}
