package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToMemory generated by hbm2java
 */
public class MobilePhoneToMemory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3277737924079884159L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileMemory mobileMemory;

	public MobilePhoneToMemory() {
	}

	public MobilePhoneToMemory(MobilePhones mobilePhones,
			MobileMemory mobileMemory) {
		this.mobilePhones = mobilePhones;
		this.mobileMemory = mobileMemory;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileMemory getMobileMemory() {
		return this.mobileMemory;
	}

	public void setMobileMemory(MobileMemory mobileMemory) {
		this.mobileMemory = mobileMemory;
	}

}
