package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToDataSpeeds generated by hbm2java
 */
public class MobilePhoneToDataSpeeds implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2084302790817988708L;
	private Long id;
	private MobileDataSpeeds mobileDataSpeeds;
	private MobilePhones mobilePhones;

	public MobilePhoneToDataSpeeds() {
	}

	public MobilePhoneToDataSpeeds(MobileDataSpeeds mobileDataSpeeds,
			MobilePhones mobilePhones) {
		this.mobileDataSpeeds = mobileDataSpeeds;
		this.mobilePhones = mobilePhones;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobileDataSpeeds getMobileDataSpeeds() {
		return this.mobileDataSpeeds;
	}

	public void setMobileDataSpeeds(MobileDataSpeeds mobileDataSpeeds) {
		this.mobileDataSpeeds = mobileDataSpeeds;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

}
