package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToGames generated by hbm2java
 */
public class MobilePhoneToGames implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4372383284150273315L;
	private Long id;
	private MobileGames mobileGames;
	private MobilePhones mobilePhones;

	public MobilePhoneToGames() {
	}

	public MobilePhoneToGames(MobileGames mobileGames, MobilePhones mobilePhones) {
		this.mobileGames = mobileGames;
		this.mobilePhones = mobilePhones;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobileGames getMobileGames() {
		return this.mobileGames;
	}

	public void setMobileGames(MobileGames mobileGames) {
		this.mobileGames = mobileGames;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

}
