package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToColors generated by hbm2java
 */
public class MobilePhoneToColors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2328699136300765690L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileColors mobileColors;

	public MobilePhoneToColors() {
	}

	public MobilePhoneToColors(MobilePhones mobilePhones,
			MobileColors mobileColors) {
		this.mobilePhones = mobilePhones;
		this.mobileColors = mobileColors;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileColors getMobileColors() {
		return this.mobileColors;
	}

	public void setMobileColors(MobileColors mobileColors) {
		this.mobileColors = mobileColors;
	}

}
