package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToCameraPrimary generated by hbm2java
 */
public class MobilePhoneToCameraPrimary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6723955887588720088L;
	private Long id;
	private MobileCameraPrimary mobileCameraPrimary;
	private MobilePhones mobilePhones;

	public MobilePhoneToCameraPrimary() {
	}

	public MobilePhoneToCameraPrimary(MobileCameraPrimary mobileCameraPrimary,
			MobilePhones mobilePhones) {
		this.mobileCameraPrimary = mobileCameraPrimary;
		this.mobilePhones = mobilePhones;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobileCameraPrimary getMobileCameraPrimary() {
		return this.mobileCameraPrimary;
	}

	public void setMobileCameraPrimary(MobileCameraPrimary mobileCameraPrimary) {
		this.mobileCameraPrimary = mobileCameraPrimary;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

}
