package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToBrowsers generated by hbm2java
 */
public class MobilePhoneToBrowsers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6877399277330725613L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileBrowsers mobileBrowsers;

	public MobilePhoneToBrowsers() {
	}

	public MobilePhoneToBrowsers(MobilePhones mobilePhones,
			MobileBrowsers mobileBrowsers) {
		this.mobilePhones = mobilePhones;
		this.mobileBrowsers = mobileBrowsers;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileBrowsers getMobileBrowsers() {
		return this.mobileBrowsers;
	}

	public void setMobileBrowsers(MobileBrowsers mobileBrowsers) {
		this.mobileBrowsers = mobileBrowsers;
	}

}
