package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToNfc generated by hbm2java
 */
public class MobilePhoneToNfc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1955371857466336779L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileNfc mobileNfc;

	public MobilePhoneToNfc() {
	}

	public MobilePhoneToNfc(MobilePhones mobilePhones, MobileNfc mobileNfc) {
		this.mobilePhones = mobilePhones;
		this.mobileNfc = mobileNfc;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileNfc getMobileNfc() {
		return this.mobileNfc;
	}

	public void setMobileNfc(MobileNfc mobileNfc) {
		this.mobileNfc = mobileNfc;
	}

}
