package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhonePhotos generated by hbm2java
 */
public class MobilePhonePhotos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8023821002221150368L;
	private Long id;
	private long phoneId;
	private String photoUrl;

	public MobilePhonePhotos() {
	}

	public MobilePhonePhotos(long phoneId, String photoUrl) {
		this.phoneId = phoneId;
		this.photoUrl = photoUrl;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getPhoneId() {
		return this.phoneId;
	}

	public void setPhoneId(long phoneId) {
		this.phoneId = phoneId;
	}

	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

}
