package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToCameraFeatures generated by hbm2java
 */
public class MobilePhoneToCameraFeatures implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1610084814301960796L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileCameraFeatures mobileCameraFeatures;

	public MobilePhoneToCameraFeatures() {
	}

	public MobilePhoneToCameraFeatures(MobilePhones mobilePhones,
			MobileCameraFeatures mobileCameraFeatures) {
		this.mobilePhones = mobilePhones;
		this.mobileCameraFeatures = mobileCameraFeatures;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileCameraFeatures getMobileCameraFeatures() {
		return this.mobileCameraFeatures;
	}

	public void setMobileCameraFeatures(
			MobileCameraFeatures mobileCameraFeatures) {
		this.mobileCameraFeatures = mobileCameraFeatures;
	}

}
