package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToRadio generated by hbm2java
 */
public class MobilePhoneToRadio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7875917002250406205L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileRadio mobileRadio;

	public MobilePhoneToRadio() {
	}

	public MobilePhoneToRadio(MobilePhones mobilePhones, MobileRadio mobileRadio) {
		this.mobilePhones = mobilePhones;
		this.mobileRadio = mobileRadio;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileRadio getMobileRadio() {
		return this.mobileRadio;
	}

	public void setMobileRadio(MobileRadio mobileRadio) {
		this.mobileRadio = mobileRadio;
	}

}
