package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToCameraSecondary generated by hbm2java
 */
public class MobilePhoneToCameraSecondary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8865633539224825643L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileCameraSecondary mobileCameraSecondary;

	public MobilePhoneToCameraSecondary() {
	}

	public MobilePhoneToCameraSecondary(MobilePhones mobilePhones,
			MobileCameraSecondary mobileCameraSecondary) {
		this.mobilePhones = mobilePhones;
		this.mobileCameraSecondary = mobileCameraSecondary;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileCameraSecondary getMobileCameraSecondary() {
		return this.mobileCameraSecondary;
	}

	public void setMobileCameraSecondary(
			MobileCameraSecondary mobileCameraSecondary) {
		this.mobileCameraSecondary = mobileCameraSecondary;
	}

}
