package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MobilePhones generated by hbm2java
 */
public class MobilePhones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6246241713987947978L;
	private Long id;
	private MobileBluetooth mobileBluetooth;
	private MobileGps mobileGps;
	private MobileChipsets mobileChipsets;
	private MobileEdge mobileEdge;
	private MobileGpu mobileGpu;
	private MobileUsb mobileUsb;
	private MobileWlan mobileWlan;
	private MobileCpu mobileCpu;
	private MobileGprs mobileGprs;
	private MobileOs mobileOs;
	private long gsmarenaId;
	private Long brandId;
	private String slug;
	private String title;
	private Long simTypeId;
	private Date announcementDate;
	private Date releaseDate;
	private String dimensions;
	private String weight;
	private String displaySize;
	private Character displayMultitouch;
	private Character soundLoudspeaker;
	private Character sound35mmjack;
	private String phonebook;
	private String callRecords;
	private String battery;
	private String standbyTime;
	private String talkTime;
	private String musicPlay;
	private String photoUrl;
	private String shortDesc;
	private String fullDesc;
	private Character isSpecial;
	private Character isFeatured;
	private Date addedOn;
	private Character isActive;
	private Character isDeleted;
	private Set<?> mobilePhoneToDataSpeedses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToAlertTypeses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToNetworkses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToMessagings = new HashSet<Object>(0);
	private Set<?> mobilePhoneToCameraFeatureses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToBrowserses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToColorses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToProtectionses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToCameraPrimaries = new HashSet<Object>(0);
	private Set<?> mobilePhoneToNfcs = new HashSet<Object>(0);
	private Set<?> mobilePhoneToMemories = new HashSet<Object>(0);
	private Set<?> mobilePhoneToDisplayTypeses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToMemoryCardslotses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToJavas = new HashSet<Object>(0);
	private Set<?> mobilePhoneToSensorses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToRadios = new HashSet<Object>(0);
	private Set<?> mobilePhoneToGameses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToFeatureses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToCameraVideos = new HashSet<Object>(0);
	private Set<?> mobilePhoneToSoundFeatureses = new HashSet<Object>(0);
	private Set<?> mobilePhoneToCameraSecondaries = new HashSet<Object>(0);
	private Set<?> mobilePhoneReviews = new HashSet<Object>(0);

	public MobilePhones() {
	}

	public MobilePhones(long gsmarenaId, String phonebook, String callRecords,
			String photoUrl) {
		this.gsmarenaId = gsmarenaId;
		this.phonebook = phonebook;
		this.callRecords = callRecords;
		this.photoUrl = photoUrl;
	}

	public MobilePhones(MobileBluetooth mobileBluetooth, MobileGps mobileGps,
			MobileChipsets mobileChipsets, MobileEdge mobileEdge,
			MobileGpu mobileGpu, MobileUsb mobileUsb, MobileWlan mobileWlan,
			MobileCpu mobileCpu, MobileGprs mobileGprs, MobileOs mobileOs,
			long gsmarenaId, Long brandId, String slug, String title,
			Long simTypeId, Date announcementDate, Date releaseDate,
			String dimensions, String weight, String displaySize,
			Character displayMultitouch, Character soundLoudspeaker,
			Character sound35mmjack, String phonebook, String callRecords,
			String battery, String standbyTime, String talkTime,
			String musicPlay, String photoUrl, String shortDesc,
			String fullDesc, Character isSpecial, Character isFeatured,
			Date addedOn, Character isActive, Character isDeleted,
			Set<?> mobilePhoneToDataSpeedses, Set<?> mobilePhoneToAlertTypeses,
			Set<?> mobilePhoneToNetworkses, Set<?> mobilePhoneToMessagings,
			Set<?> mobilePhoneToCameraFeatureses, Set<?> mobilePhoneToBrowserses,
			Set<?> mobilePhoneToColorses, Set<?> mobilePhoneToProtectionses,
			Set<?> mobilePhoneToCameraPrimaries, Set<?> mobilePhoneToNfcs,
			Set<?> mobilePhoneToMemories, Set<?> mobilePhoneToDisplayTypeses,
			Set<?> mobilePhoneToMemoryCardslotses, Set<?> mobilePhoneToJavas,
			Set<?> mobilePhoneToSensorses, Set<?> mobilePhoneToRadios,
			Set<?> mobilePhoneToGameses, Set<?> mobilePhoneToFeatureses,
			Set<?> mobilePhoneToCameraVideos, Set<?> mobilePhoneToSoundFeatureses,
			Set<?> mobilePhoneToCameraSecondaries,Set<?> mobilePhoneReviews) {
		this.mobileBluetooth = mobileBluetooth;
		this.mobileGps = mobileGps;
		this.mobileChipsets = mobileChipsets;
		this.mobileEdge = mobileEdge;
		this.mobileGpu = mobileGpu;
		this.mobileUsb = mobileUsb;
		this.mobileWlan = mobileWlan;
		this.mobileCpu = mobileCpu;
		this.mobileGprs = mobileGprs;
		this.mobileOs = mobileOs;
		this.gsmarenaId = gsmarenaId;
		this.brandId = brandId;
		this.slug = slug;
		this.title = title;
		this.simTypeId = simTypeId;
		this.announcementDate = announcementDate;
		this.releaseDate = releaseDate;
		this.dimensions = dimensions;
		this.weight = weight;
		this.displaySize = displaySize;
		this.displayMultitouch = displayMultitouch;
		this.soundLoudspeaker = soundLoudspeaker;
		this.sound35mmjack = sound35mmjack;
		this.phonebook = phonebook;
		this.callRecords = callRecords;
		this.battery = battery;
		this.standbyTime = standbyTime;
		this.talkTime = talkTime;
		this.musicPlay = musicPlay;
		this.photoUrl = photoUrl;
		this.shortDesc = shortDesc;
		this.fullDesc = fullDesc;
		this.isSpecial = isSpecial;
		this.isFeatured = isFeatured;
		this.addedOn = addedOn;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.mobilePhoneToDataSpeedses = mobilePhoneToDataSpeedses;
		this.mobilePhoneToAlertTypeses = mobilePhoneToAlertTypeses;
		this.mobilePhoneToNetworkses = mobilePhoneToNetworkses;
		this.mobilePhoneToMessagings = mobilePhoneToMessagings;
		this.mobilePhoneToCameraFeatureses = mobilePhoneToCameraFeatureses;
		this.mobilePhoneToBrowserses = mobilePhoneToBrowserses;
		this.mobilePhoneToColorses = mobilePhoneToColorses;
		this.mobilePhoneToProtectionses = mobilePhoneToProtectionses;
		this.mobilePhoneToCameraPrimaries = mobilePhoneToCameraPrimaries;
		this.mobilePhoneToNfcs = mobilePhoneToNfcs;
		this.mobilePhoneToMemories = mobilePhoneToMemories;
		this.mobilePhoneToDisplayTypeses = mobilePhoneToDisplayTypeses;
		this.mobilePhoneToMemoryCardslotses = mobilePhoneToMemoryCardslotses;
		this.mobilePhoneToJavas = mobilePhoneToJavas;
		this.mobilePhoneToSensorses = mobilePhoneToSensorses;
		this.mobilePhoneToRadios = mobilePhoneToRadios;
		this.mobilePhoneToGameses = mobilePhoneToGameses;
		this.mobilePhoneToFeatureses = mobilePhoneToFeatureses;
		this.mobilePhoneToCameraVideos = mobilePhoneToCameraVideos;
		this.mobilePhoneToSoundFeatureses = mobilePhoneToSoundFeatureses;
		this.mobilePhoneToCameraSecondaries = mobilePhoneToCameraSecondaries;
		this.setMobilePhoneReviews(mobilePhoneReviews);
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobileBluetooth getMobileBluetooth() {
		return this.mobileBluetooth;
	}

	public void setMobileBluetooth(MobileBluetooth mobileBluetooth) {
		this.mobileBluetooth = mobileBluetooth;
	}

	public MobileGps getMobileGps() {
		return this.mobileGps;
	}

	public void setMobileGps(MobileGps mobileGps) {
		this.mobileGps = mobileGps;
	}

	public MobileChipsets getMobileChipsets() {
		return this.mobileChipsets;
	}

	public void setMobileChipsets(MobileChipsets mobileChipsets) {
		this.mobileChipsets = mobileChipsets;
	}

	public MobileEdge getMobileEdge() {
		return this.mobileEdge;
	}

	public void setMobileEdge(MobileEdge mobileEdge) {
		this.mobileEdge = mobileEdge;
	}

	public MobileGpu getMobileGpu() {
		return this.mobileGpu;
	}

	public void setMobileGpu(MobileGpu mobileGpu) {
		this.mobileGpu = mobileGpu;
	}

	public MobileUsb getMobileUsb() {
		return this.mobileUsb;
	}

	public void setMobileUsb(MobileUsb mobileUsb) {
		this.mobileUsb = mobileUsb;
	}

	public MobileWlan getMobileWlan() {
		return this.mobileWlan;
	}

	public void setMobileWlan(MobileWlan mobileWlan) {
		this.mobileWlan = mobileWlan;
	}

	public MobileCpu getMobileCpu() {
		return this.mobileCpu;
	}

	public void setMobileCpu(MobileCpu mobileCpu) {
		this.mobileCpu = mobileCpu;
	}

	public MobileGprs getMobileGprs() {
		return this.mobileGprs;
	}

	public void setMobileGprs(MobileGprs mobileGprs) {
		this.mobileGprs = mobileGprs;
	}

	public MobileOs getMobileOs() {
		return this.mobileOs;
	}

	public void setMobileOs(MobileOs mobileOs) {
		this.mobileOs = mobileOs;
	}

	public long getGsmarenaId() {
		return this.gsmarenaId;
	}

	public void setGsmarenaId(long gsmarenaId) {
		this.gsmarenaId = gsmarenaId;
	}

	public Long getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Long getSimTypeId() {
		return this.simTypeId;
	}

	public void setSimTypeId(Long simTypeId) {
		this.simTypeId = simTypeId;
	}

	public Date getAnnouncementDate() {
		return this.announcementDate;
	}

	public void setAnnouncementDate(Date announcementDate) {
		this.announcementDate = announcementDate;
	}

	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public String getDimensions() {
		return this.dimensions;
	}

	public void setDimensions(String dimensions) {
		this.dimensions = dimensions;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getDisplaySize() {
		return this.displaySize;
	}

	public void setDisplaySize(String displaySize) {
		this.displaySize = displaySize;
	}

	public Character getDisplayMultitouch() {
		return this.displayMultitouch;
	}

	public void setDisplayMultitouch(Character displayMultitouch) {
		this.displayMultitouch = displayMultitouch;
	}

	public Character getSoundLoudspeaker() {
		return this.soundLoudspeaker;
	}

	public void setSoundLoudspeaker(Character soundLoudspeaker) {
		this.soundLoudspeaker = soundLoudspeaker;
	}

	public Character getSound35mmjack() {
		return this.sound35mmjack;
	}

	public void setSound35mmjack(Character sound35mmjack) {
		this.sound35mmjack = sound35mmjack;
	}

	public String getPhonebook() {
		return this.phonebook;
	}

	public void setPhonebook(String phonebook) {
		this.phonebook = phonebook;
	}

	public String getCallRecords() {
		return this.callRecords;
	}

	public void setCallRecords(String callRecords) {
		this.callRecords = callRecords;
	}

	public String getBattery() {
		return this.battery;
	}

	public void setBattery(String battery) {
		this.battery = battery;
	}

	public String getStandbyTime() {
		return this.standbyTime;
	}

	public void setStandbyTime(String standbyTime) {
		this.standbyTime = standbyTime;
	}

	public String getTalkTime() {
		return this.talkTime;
	}

	public void setTalkTime(String talkTime) {
		this.talkTime = talkTime;
	}

	public String getMusicPlay() {
		return this.musicPlay;
	}

	public void setMusicPlay(String musicPlay) {
		this.musicPlay = musicPlay;
	}

	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public String getFullDesc() {
		return this.fullDesc;
	}

	public void setFullDesc(String fullDesc) {
		this.fullDesc = fullDesc;
	}

	public Character getIsSpecial() {
		return this.isSpecial;
	}

	public void setIsSpecial(Character isSpecial) {
		this.isSpecial = isSpecial;
	}

	public Character getIsFeatured() {
		return this.isFeatured;
	}

	public void setIsFeatured(Character isFeatured) {
		this.isFeatured = isFeatured;
	}

	public Date getAddedOn() {
		return this.addedOn;
	}

	public void setAddedOn(Date addedOn) {
		this.addedOn = addedOn;
	}

	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	public Character getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Character isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<?> getMobilePhoneToDataSpeedses() {
		return this.mobilePhoneToDataSpeedses;
	}

	public void setMobilePhoneToDataSpeedses(Set<?> mobilePhoneToDataSpeedses) {
		this.mobilePhoneToDataSpeedses = mobilePhoneToDataSpeedses;
	}

	public Set<?> getMobilePhoneToAlertTypeses() {
		return this.mobilePhoneToAlertTypeses;
	}

	public void setMobilePhoneToAlertTypeses(Set<?> mobilePhoneToAlertTypeses) {
		this.mobilePhoneToAlertTypeses = mobilePhoneToAlertTypeses;
	}

	public Set<?> getMobilePhoneToNetworkses() {
		return this.mobilePhoneToNetworkses;
	}

	public void setMobilePhoneToNetworkses(Set<?> mobilePhoneToNetworkses) {
		this.mobilePhoneToNetworkses = mobilePhoneToNetworkses;
	}

	public Set<?> getMobilePhoneToMessagings() {
		return this.mobilePhoneToMessagings;
	}

	public void setMobilePhoneToMessagings(Set<?> mobilePhoneToMessagings) {
		this.mobilePhoneToMessagings = mobilePhoneToMessagings;
	}

	public Set<?> getMobilePhoneToCameraFeatureses() {
		return this.mobilePhoneToCameraFeatureses;
	}

	public void setMobilePhoneToCameraFeatureses(
			Set<?> mobilePhoneToCameraFeatureses) {
		this.mobilePhoneToCameraFeatureses = mobilePhoneToCameraFeatureses;
	}

	public Set<?> getMobilePhoneToBrowserses() {
		return this.mobilePhoneToBrowserses;
	}

	public void setMobilePhoneToBrowserses(Set<?> mobilePhoneToBrowserses) {
		this.mobilePhoneToBrowserses = mobilePhoneToBrowserses;
	}

	public Set<?> getMobilePhoneToColorses() {
		return this.mobilePhoneToColorses;
	}

	public void setMobilePhoneToColorses(Set<?> mobilePhoneToColorses) {
		this.mobilePhoneToColorses = mobilePhoneToColorses;
	}

	public Set<?> getMobilePhoneToProtectionses() {
		return this.mobilePhoneToProtectionses;
	}

	public void setMobilePhoneToProtectionses(Set<?> mobilePhoneToProtectionses) {
		this.mobilePhoneToProtectionses = mobilePhoneToProtectionses;
	}

	public Set<?> getMobilePhoneToCameraPrimaries() {
		return this.mobilePhoneToCameraPrimaries;
	}

	public void setMobilePhoneToCameraPrimaries(Set<?> mobilePhoneToCameraPrimaries) {
		this.mobilePhoneToCameraPrimaries = mobilePhoneToCameraPrimaries;
	}

	public Set<?> getMobilePhoneToNfcs() {
		return this.mobilePhoneToNfcs;
	}

	public void setMobilePhoneToNfcs(Set<?> mobilePhoneToNfcs) {
		this.mobilePhoneToNfcs = mobilePhoneToNfcs;
	}

	public Set<?> getMobilePhoneToMemories() {
		return this.mobilePhoneToMemories;
	}

	public void setMobilePhoneToMemories(Set<?> mobilePhoneToMemories) {
		this.mobilePhoneToMemories = mobilePhoneToMemories;
	}

	public Set<?> getMobilePhoneToDisplayTypeses() {
		return this.mobilePhoneToDisplayTypeses;
	}

	public void setMobilePhoneToDisplayTypeses(Set<?> mobilePhoneToDisplayTypeses) {
		this.mobilePhoneToDisplayTypeses = mobilePhoneToDisplayTypeses;
	}

	public Set<?> getMobilePhoneToMemoryCardslotses() {
		return this.mobilePhoneToMemoryCardslotses;
	}

	public void setMobilePhoneToMemoryCardslotses(
			Set<?> mobilePhoneToMemoryCardslotses) {
		this.mobilePhoneToMemoryCardslotses = mobilePhoneToMemoryCardslotses;
	}

	public Set<?> getMobilePhoneToJavas() {
		return this.mobilePhoneToJavas;
	}

	public void setMobilePhoneToJavas(Set<?> mobilePhoneToJavas) {
		this.mobilePhoneToJavas = mobilePhoneToJavas;
	}

	public Set<?> getMobilePhoneToSensorses() {
		return this.mobilePhoneToSensorses;
	}

	public void setMobilePhoneToSensorses(Set<?> mobilePhoneToSensorses) {
		this.mobilePhoneToSensorses = mobilePhoneToSensorses;
	}

	public Set<?> getMobilePhoneToRadios() {
		return this.mobilePhoneToRadios;
	}

	public void setMobilePhoneToRadios(Set<?> mobilePhoneToRadios) {
		this.mobilePhoneToRadios = mobilePhoneToRadios;
	}

	public Set<?> getMobilePhoneToGameses() {
		return this.mobilePhoneToGameses;
	}

	public void setMobilePhoneToGameses(Set<?> mobilePhoneToGameses) {
		this.mobilePhoneToGameses = mobilePhoneToGameses;
	}

	public Set<?> getMobilePhoneToFeatureses() {
		return this.mobilePhoneToFeatureses;
	}

	public void setMobilePhoneToFeatureses(Set<?> mobilePhoneToFeatureses) {
		this.mobilePhoneToFeatureses = mobilePhoneToFeatureses;
	}

	public Set<?> getMobilePhoneToCameraVideos() {
		return this.mobilePhoneToCameraVideos;
	}

	public void setMobilePhoneToCameraVideos(Set<?> mobilePhoneToCameraVideos) {
		this.mobilePhoneToCameraVideos = mobilePhoneToCameraVideos;
	}

	public Set<?> getMobilePhoneToSoundFeatureses() {
		return this.mobilePhoneToSoundFeatureses;
	}

	public void setMobilePhoneToSoundFeatureses(Set<?> mobilePhoneToSoundFeatureses) {
		this.mobilePhoneToSoundFeatureses = mobilePhoneToSoundFeatureses;
	}

	public Set<?> getMobilePhoneToCameraSecondaries() {
		return this.mobilePhoneToCameraSecondaries;
	}

	public void setMobilePhoneToCameraSecondaries(
			Set<?> mobilePhoneToCameraSecondaries) {
		this.mobilePhoneToCameraSecondaries = mobilePhoneToCameraSecondaries;
	}

	public Set<?> getMobilePhoneReviews() {
		return mobilePhoneReviews;
	}

	public void setMobilePhoneReviews(Set<?> mobilePhoneReviews) {
		this.mobilePhoneReviews = mobilePhoneReviews;
	}
	
	

}
