package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToSensors generated by hbm2java
 */
public class MobilePhoneToSensors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5883897338164828789L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileSensors mobileSensors;

	public MobilePhoneToSensors() {
	}

	public MobilePhoneToSensors(MobilePhones mobilePhones,
			MobileSensors mobileSensors) {
		this.mobilePhones = mobilePhones;
		this.mobileSensors = mobileSensors;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileSensors getMobileSensors() {
		return this.mobileSensors;
	}

	public void setMobileSensors(MobileSensors mobileSensors) {
		this.mobileSensors = mobileSensors;
	}

}
