package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToFeatures generated by hbm2java
 */
public class MobilePhoneToFeatures implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3894787310209553589L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileFeatures mobileFeatures;

	public MobilePhoneToFeatures() {
	}

	public MobilePhoneToFeatures(MobilePhones mobilePhones,
			MobileFeatures mobileFeatures) {
		this.mobilePhones = mobilePhones;
		this.mobileFeatures = mobileFeatures;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileFeatures getMobileFeatures() {
		return this.mobileFeatures;
	}

	public void setMobileFeatures(MobileFeatures mobileFeatures) {
		this.mobileFeatures = mobileFeatures;
	}

}
