package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToJava generated by hbm2java
 */
public class MobilePhoneToJava implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6783524635696706761L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileJava mobileJava;

	public MobilePhoneToJava() {
	}

	public MobilePhoneToJava(MobilePhones mobilePhones, MobileJava mobileJava) {
		this.mobilePhones = mobilePhones;
		this.mobileJava = mobileJava;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileJava getMobileJava() {
		return this.mobileJava;
	}

	public void setMobileJava(MobileJava mobileJava) {
		this.mobileJava = mobileJava;
	}

}
