package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobilePhoneToDisplayTypes generated by hbm2java
 */
public class MobilePhoneToDisplayTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -678470467211707280L;
	private Long id;
	private MobilePhones mobilePhones;
	private MobileDisplayTypes mobileDisplayTypes;

	public MobilePhoneToDisplayTypes() {
	}

	public MobilePhoneToDisplayTypes(MobilePhones mobilePhones,
			MobileDisplayTypes mobileDisplayTypes) {
		this.mobilePhones = mobilePhones;
		this.mobileDisplayTypes = mobileDisplayTypes;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public MobilePhones getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(MobilePhones mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public MobileDisplayTypes getMobileDisplayTypes() {
		return this.mobileDisplayTypes;
	}

	public void setMobileDisplayTypes(MobileDisplayTypes mobileDisplayTypes) {
		this.mobileDisplayTypes = mobileDisplayTypes;
	}

}
