package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PostsComments generated by hbm2java
 */
public class PostsComments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6668818276712387560L;
	private Long id;
	private Posts posts;
	private String name;
	private String email;
	private String content;
	private Date addedOn;
	private Character isDeleted;

	public PostsComments() {
	}

	public PostsComments(Date addedOn) {
		this.addedOn = addedOn;
	}

	public PostsComments(Posts posts, String name, String email,
			String content, Date addedOn, Character isDeleted) {
		this.posts = posts;
		this.name = name;
		this.email = email;
		this.content = content;
		this.addedOn = addedOn;
		this.isDeleted = isDeleted;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Posts getPosts() {
		return this.posts;
	}

	public void setPosts(Posts posts) {
		this.posts = posts;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getAddedOn() {
		return this.addedOn;
	}

	public void setAddedOn(Date addedOn) {
		this.addedOn = addedOn;
	}

	public Character getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Character isDeleted) {
		this.isDeleted = isDeleted;
	}

}
