package com.imc.framework.bean;
// Generated Mar 6, 2013 10:49:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Posts generated by hbm2java
 */
public class Posts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8116072168933123140L;
	private Long id;
	private String slug;
	private String title;
	private String shortContent;
	private String content;
	private String tags;
	private String postType;
	private Date addedOn;
	private Character isActive;
	private Character isDeleted;
	private Set<?> postsCommentses = new HashSet<Object>(0);

	public Posts() {
	}

	public Posts(Date addedOn) {
		this.addedOn = addedOn;
	}

	public Posts(String slug, String title, String shortContent,
			String content, String tags, String postType, Date addedOn,
			Character isActive, Character isDeleted, Set<?> postsCommentses) {
		this.slug = slug;
		this.title = title;
		this.shortContent = shortContent;
		this.content = content;
		this.tags = tags;
		this.postType = postType;
		this.addedOn = addedOn;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.postsCommentses = postsCommentses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getShortContent() {
		return this.shortContent;
	}

	public void setShortContent(String shortContent) {
		this.shortContent = shortContent;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public String getPostType() {
		return this.postType;
	}

	public void setPostType(String postType) {
		this.postType = postType;
	}

	public Date getAddedOn() {
		return this.addedOn;
	}

	public void setAddedOn(Date addedOn) {
		this.addedOn = addedOn;
	}

	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	public Character getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Character isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<?> getPostsCommentses() {
		return this.postsCommentses;
	}

	public void setPostsCommentses(Set<?> postsCommentses) {
		this.postsCommentses = postsCommentses;
	}

}
